### ISSUE TITLE
P.281: スクリプト inspect_camera_pi.py がエラーで終了します

### ISSUE THREAD

**Issue by renkin3q** [karaage0703/karaage-ai-book#16]
**ページ数**

P.281 のテキストボックス

**内容**

スクリプト inspect_camera_pi.py がエラーで終了してしまいます。
手順に変わりはないか、ご確認頂けないでしょうか。

私の環境：
- Raspberry Pi 3 B+
- Raspberry Pi OS 10 (buster)

実行時のログ：
```
$ python3 inspect_camera_pi.py -l="labels.txt" -m="my_model_aug.h5"
2021-01-04 17:49:17.193270: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
['choki', 'gu', 'pa']
Traceback (most recent call last):
  File "inspect_camera_pi.py", line 30, in <module>
    model_pred = tf.keras.models.load_model(args.model)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

```
**コメント**

**Comment by karaage0703** [comment]
@renkin3q 
さん
報告ありがとうございます。
まだ実機で確認できていませんが、エラーメッセージで検索したところ、バージョンの不一致によるエラーの可能性が高そうです。
また、こちらで実機で確認して、インストールスクリプトのアップデートを行う予定です。
取り急ぎの回答となりますが、ラズパイ側で以下のコマンドを実行することで動くようになるかもしれません。

```sh
$ sudo pip3 uninstall h5py
$ sudo pip3 install h5py==2.10.0
```

書籍にも記載した通り、ディープラーニング関係のライブラリは、バージョン変更が激しく、簡単な例でもこのようなバージョンの差異によるエラーが起こり得ます。書籍執筆時点では動いていたものが動かなくなるケースがあることご容赦ください。

その分、情報もネットに多くあります。もし今後、書籍の応用以外のことをやろうとして困ったときなどはエラーメッセージで検索すると、情報でてくることが多いです。

今回も`AttributeError: 'str' object has no attribute 'decode'`で検索したら以下の記事が出てきました。

[【Keras】エラー 'str' object has no attribute 'decode'について](https://qiita.com/Hiroki-Fujimoto/items/b078bfb680fb710c38c1)

**Comment by karaage0703** [comment]
@renkin3q さん
他の読者の方も困っていたかもしれないので、教えていただき感謝しております。
バージョンはまた変わりそうなので、サポートサイトのよくある質問に本内容を追記させていただきたいと思います。
